### ISSUE TITLE
Sourcemaps in npm distribution

### ISSUE THREAD

**Issue by gmmorris** [zentrick/iab-vast-model#45]
Hi y'all,
It seems you're including source maps in the npm module you distribute.
Would it be possible to rerelease without the sourcemaps as it screws up the devtools when debugging a bundled version?

We could strip them out on our end, but before doing that on our end I thought I'd ask, as it seems to us like an NPM distribution probably shouldn't force Sourcemaps on you when you import the production version.

Thanks

**Comment by timdp** [comment]
Hi there. :slightly_smiling_face: 

The reasoning behind this is that in Node, you may want the source maps, whereas on the front end, you're likely to use your own bundler, which can either build the package from source and perform tree shaking, or strip the source maps from the compiled code.

However, if it's giving you trouble, I wouldn't mind turning off source maps. I'd just like to explore the option of building from source though. Would that be a possibility at all?

**Comment by gmmorris** [comment]
Hey Tim,
Thanks for the explanation, it makes sense but I feel it would be best to have two builds bundled into the package - with the default not having source maps baked into it.

Building from source is a possibility, obviously, it just means we have to define custom aliases in Webpack / Babel to make this work (to point to 'iab-vast-model/src/index' instead of just 'iab-vast-model' when importing). It's an annoyance, but not a major one, so obviously it's up to you.

I'd just say, in the friendliest tone possible, that this is the only package we use that forces us to bypass the default npm export and build the source just to avoid Source Maps... so, I suspect the standard would be to not package the source maps in the production build.
But that's just my feeling... the Javascript Community and Standard Practices rarely go hand in hand :)

**Comment by gmmorris** [comment]
Actually looks like it forces us to also put manual hacks into our loader definitions, which makes it a much bigger annoyance.  :-(

The rule of thumb definitely seems to be that the package's *main* should be produciton es5, and the 'jsnext:main' shoudl be the es6 so you can build yourself.
I think its expected that if someone wants source maps they'll build the es6 themselves as part of their build process... but I may be wrong. 🤷

**Comment by timdp** [comment]
> to point to 'iab-vast-model/src/index' instead of just 'iab-vast-model' when importing

As you mention, that's what package.json `"jsnext:main"` accomplishes though, right? Since you're using Webpack, could it be that we just need to rename that to the newer `"module"` for it to work? With Rollup, both generally work, but I have no idea about Webpack. At any rate, it couldn't hurt to update.

> the package's `"main"` should be production es5

I agree, but "production" can mean browser or Node. In Node, it does make sense to have the source maps available. There's also the nonstandard `"browser"` field in package.json, which I believe is intended as an ES5 browser build. However, in the absence of module loaders, I fear it might need to be a full bundle rather than just `index.js`, which would potentially break tree shaking in your build.

But wouldn't it be better to build from the ES6 source anyway? At Zentrick, we have Rollup configured to build all our own packages from source, which allows us to optimize tree shaking and other types of dead code elimination and deduplication.

I don't want either of us to spend too much time on this, so the quickest path for me would be to just disable source maps in the production build until someone complains. It just _seems_ like something Webpack should be able to handle quite elegantly, but if it can't, I'll happily accept that and move on. :slightly_smiling_face:

**Comment by gmmorris** [comment]
wait off for now, I'll see if I can tell Webpack to build iab-vast-model but not other node_modules.
In general I found enabling support for jsnext:main to be more trouble than it's worth because many package maintainers don't set it up right and don't expose their .babelrc which means you can't build properly....

But I'll see if I can find a solution.
If you want to release a new version without source maps it'll make our lives easier, but sounds like it is actually helpful for you so I'll see if I can find a solution that won't be too hacky for us and will allow you to keep the added value you have. :)

**Comment by timdp** [comment]
Ah, yeah, the different Babel setups have also bitten us. We've invested a lot of time in programmatically configuring Rollup to suit our exact needs, so it might indeed not be as straightforward.

For now, I'll just disable the source maps and publish a new version. They're not worth the trouble.

**Comment by gmmorris** [comment]
Thanks Tim :)
